#
# ci script using travis
#
# TODO: use qt5
#
language: cpp

compiler: gcc

before_install:
- cat /etc/issue
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq
- sudo apt-get install -qq cmake
- sudo apt-get install -qq qt4-dev-tools
#- sudo apt-get install -qq qttools5-dev-tools
#
#- sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
#- sudo pip install cpp-coveralls --use-mirrors

before_script:
- mkdir build
- cd build
- cmake ..

after_success:
#- coveralls --exclude bin --exclude deps --exclude doc --exclude var
  
script:
#- qmake -qt=qt5 -v
#- qmake -qt=qt5
- make

notifications:
 email:
   - kcris@sogetthis.com
 
 on_success: change
 
 on_failure: always
